name: Process Internship Submissions

on:
  issues:
    types: [opened]

jobs:
  process_internship:
    if: contains(github.event.issue.labels.*.name, 'internship-submission')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install PyYAML
        run: pip install pyyaml

      - name: Extract issue data and generate markdown
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          mkdir -p internships
          python3 .github/scripts/process_issue.py

      - name: Commit and push markdown file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add internship: ${{ github.event.issue.title }}"
          branch: ${{ github.ref }}
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }} 

permissions:
  contents: write
  issues: write 